### ISSUE TITLE
linktool produce Django migrations

### ISSUE THREAD

**Issue by Hwesta** [artefactual/archivematica-devtools#31]
linktool currently produces SQL, but as of Archivematica 1.5 migrations are done using Django migrations instead of SQL migrations.  linktool needs to be updated to produce Django migration output.

**Comment by chvck** [comment]
As a general question about this, I presume that as the linktool generates standard SQL that it'll still work with 1.5 even without being updated to use migrations? I believe that we're targeting 1.5 but I have a 1.4 install so haven't been able to test yet.

**Comment by Hwesta** [comment]
The SQL that linktool generates should be runnable against an Archivematica 1.5 system.  The old system of using `src/MCPServer/share/mysql_dev.sql` doesn't exist, so the output can't be committed and used in packages.  That sounds like it's fine for your use case, though.

The migration system in Archivematica shifted to use Django migrations, so the output of this isn't useful for making migrations intended to be committed to the Archivematica repo anymore, which is what I want to fix.

**Comment by sevein** [comment]
linktool is deprecated, see https://github.com/archivematica/Issues/issues/68 for more details.
