### ISSUE TITLE
Problem: reindex-index-data script sets size 0 always

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica-devtools#48]

**Comment by jhsimpson** [comment]
This problem has been reproduced when re-indexing uncompressed aips.  When an aip is indexed within an Archivematica pipeline, the size is set correctly in the ES index.  However, when the same aip is deleted from the ES index and then reindexed using rebuild-elasticsearch-aip-index-from-files, the size shows as 0 in ES.

It is possible that this script should be calculating the size of the aip on disk and then passing it to the index_aip method here? 
https://github.com/artefactual/archivematica-devtools/blob/master/tools/rebuild-elasticsearch-aip-index-from-files#L140

**Comment by marktriggs** [comment]
Hi @jhsimpson,

We've had a look at this one and have a commit ready to go.  Assuming we're not totally off the rails, are you happy for us to send a PR against master?:

 https://github.com/hudmol/archivematica-devtools/commit/1fd49faf2b415a4f4229da832445d22b35c262f4

Thanks,
Mark

**Comment by jhsimpson** [comment]
yes please, this looks like a good approach.  Put up a PR and we can test it out.
