### ISSUE TITLE
Problem: rebuild-transfer-backlog fails in 1.7

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica-devtools#52]
This is the traceback:

<pre>
Traceback (most recent call last):
  File "rebuild-transfer-backlog", line 185, in <module>
    main()
  File "rebuild-transfer-backlog", line 173, in main
    process_transfer(es_client, os.path.join(transfer_backlog_dir, directory), sharedDirectory)
  File "rebuild-transfer-backlog", line 106, in process_transfer
    elasticSearchFunctions.connect_and_index_files('transfers', 'transferfile', uuid, path)  # AM 1.5
AttributeError: 'module' object has no attribute 'connect_and_index_files'
</pre>

**Comment by sevein** [comment]
Should this be added to the 1.7 project?

**Comment by sevein** [comment]
Tentative fix here: https://github.com/artefactual/archivematica/pull/894.

**Comment by mamedin** [comment]
I tested the new `rebuild-transfer-backlog` command and it works fine.
👍
